### ISSUE TITLE
Troubleshoot test failures for verifyBasicSearchCancerTypeKeyword on dev-ac

### ISSUE THREAD

**Issue by SupriyaSaxena0605** [NCIOCPL/cgov-digital-platform-qa#212]
following tests failed for the test data : AIDS-Related Lymphoma
verifyBasicSearchCancerTypeKeyword
verifyBasicSearchCancerTypeKeywordAge
verifyBasicSearchCancerTypeKeywordAgeZipCode

Here is the error:

Feb 25, 2020 11:22:34 AM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.

java.lang.AssertionError: query param doesnt match for cancer type expected [C3471] but found [C94797]
Expected :C3471
Actual   :C94797
<Click to see difference>

	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at gov.cancer.tests.cts.CTS_BasicSearchFunctionality_Test.lambda$verifyBasicSearchCancerTypeKeyword$0(CTS_BasicSearchFunctionality_Test.java:39)
	at gov.cancer.tests.TestRunner.runImplementation(TestRunner.java:184)
	at gov.cancer.tests.TestRunner.run(TestRunner.java:146)
	at gov.cancer.tests.cts.CTS_BasicSearchFunctionality_Test.verifyBasicSearchCancerTypeKeyword(CTS_BasicSearchFunctionality_Test.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)

**Comment by kate-mashkina** [comment]
After re-running CTS suite against new ODE above error could not be reproduced - please verify that the issue still persist or ticket is closed @SupriyaSaxena0605 
Also, **java.util.prefs.WindowsPreferences** appears to be an issue with locally installed JDK
